### ISSUE TITLE
Pup?

### ISSUE THREAD

**Issue by ghost** [coffeemood/grabbySub2#3]
When I run the script, it allows me to choose a movie and then it gives error; 
`_/bin/sh: 1: pup: not found_` 
I never heard of "pup" command so I am confused. Any ideas?

And I am running Linux Debian 8 with python 2.7 (it would be also useful to make script compatible with python 3.5)

**Comment by ghost** [comment]
Also when I try to install it, it gives me this;
`E: Unable to locate package pup`

**Comment by coffeemood** [comment]
Hi, 

`pup` is a html parser that needs to be installed separately before you can use grappySub. Please follow the installation instructions [here](https://github.com/ericchiang/pup) , it's pretty straight forward.

**Comment by ghost** [comment]
Ohh, I was searching for "pup" for a while now but nothing came up so I was lost. Thanks!

I see you need to install Go as well for pup to work which then again for grabbySub2 to work, maybe you could try to write new version on different html parser? lxml is quite simple too and doesn't require Go to be installed but thats just an Idea!

**Comment by coffeemood** [comment]
Yeah I've been thinking on that for a while as well, since not a lot of people know about `pup`, and it's kind of a burden to install, but I've kept it on because of its performance. However, I'm definitely looking into rewriting many parts of this script as well as introducing new features. 

Thanks for the input! :+1:

**Comment by ghost** [comment]
Waiting for an update then! I was thinking about including this script in my personal assistant (Heinrichy, you can check it out in my profile) so I will be definitely  interested in it.

Closing the issue.
